version: '2'
services:
  graphdb:
    image: neo4j:4.1
    container_name: graphdb-webinar
    restart: always
    hostname: graphdb-webinar
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - vol1:/data
      - ./db-plugins:/var/lib/neo4j/plugins
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none
volumes:
  vol1: